---
name: ci
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master

jobs:
  lint:
    name: flake8 lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: install lint dependancies
        run: python3 -m pip install flake8
      - name: flake8
        run: flake8 scodec 
  pip:
    name: python package install
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install scodec
        run: |
          python3 -m pip install .
          python3 -c 'import scodec; print("Success on version: {}".format(scodec.__version__))'